package:
    type:           yii2-extension
    name:           yii2-theme-dataserv
    title:          DataServ Theme for hiqdev/yii2-thememanager
    headline:       Yii2 DataServ Theme
    license:        proprietary
    keywords:       dataserv, theme, extension, yii2
    namespace:      hiqdev\themes\dataserv
    description:    |
        This package provides DataServ theme for [Yii2 framework](http://yiiframework.com).
